[tox]
envlist = py312-django{42,52},quality,package
requires = tox-uv>=1

[pycodestyle]
exclude = .git,.tox
max-line-length = 120

[pydocstyle]
ignore = D200,D203,D212

[pytest]
DJANGO_SETTINGS_MODULE = workbench.settings
addopts = --cov=google_drive --cov-report term-missing --durations=10
norecursedirs = .* requirements

[testenv]
runner = uv-venv-lock-runner
allowlist_externals =
    make
    mkdir
    rm
dependency_groups =
    django52: test
    django42: django42
setenv =
    DJANGO_SETTINGS_MODULE = workbench.settings
    SCREENSHOT_DIR={toxinidir}/var/logs
    SELENIUM_DRIVER_LOG_DIR={toxinidir}/var/logs
commands =
    mkdir -p {toxinidir}/var/logs
    rm -rf {toxinidir}/var/logs/*
    pytest {posargs}
    make validate_translations

[testenv:quality]
runner = uv-venv-lock-runner
allowlist_externals =
    make
dependency_groups =
    quality
commands =
    pylint src/google_drive
    pycodestyle src/google_drive
    make selfcheck

[testenv:package]
runner = uv-venv-lock-runner
dependency_groups =
    package
commands =
    python -m build
    twine check dist/*
